global:
  resolve_timeout: 5m

route:
  receiver: technova-webhook
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 2h

receivers:
  - name: technova-webhook
    webhook_configs:
      - url: http://webhook-listener:5001/
        send_resolved: true
