[infra]
srv-infra ansible_host=10.0.0.10

[apps]
srv-apps ansible_host=10.0.0.20

[automation]
srv-auto ansible_host=10.0.0.30 ansible_connection=local

[monitoring]
srv-monit ansible_host=10.0.0.40

[all:vars]
ansible_user=deploy
ansible_ssh_private_key_file=/home/deploy/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
